[0m23:30:38.316443 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748b018c7fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748afdf08bc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748afefd4380>]}


============================== 23:30:38.321532 | 2a9c450e-78b5-4ad1-958a-ba9fa41cd957 ==============================
[0m23:30:38.321532 [info ] [MainThread]: Running with dbt=1.10.10
[0m23:30:38.322218 [debug] [MainThread]: running dbt with arguments {'empty': 'None', 'use_colors': 'True', 'static_parser': 'True', 'write_json': 'True', 'profiles_dir': '/workspaces/CI-CD/src/dbt', 'partial_parse': 'True', 'printer_width': '80', 'target_path': 'None', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt seed', 'debug': 'False', 'fail_fast': 'False', 'version_check': 'True', 'log_path': '/workspaces/CI-CD/src/dbt/logs', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'no_print': 'None', 'cache_selected_only': 'False', 'log_format': 'default', 'use_experimental_parser': 'False', 'introspect': 'True', 'quiet': 'False'}
[0m23:30:40.683842 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '2a9c450e-78b5-4ad1-958a-ba9fa41cd957', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748aee244890>]}
[0m23:30:40.763262 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '2a9c450e-78b5-4ad1-958a-ba9fa41cd957', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748afe3cda30>]}
[0m23:30:40.764529 [info ] [MainThread]: Registered adapter: snowflake=1.10.0
[0m23:30:40.920387 [debug] [MainThread]: checksum: 502a0dc23e9052e1ae09f7c44ee219ef7a02dfea7e7d66580d54c304c14d553b, vars: {}, profile: , target: , version: 1.10.10
[0m23:30:40.921610 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m23:30:40.922411 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '2a9c450e-78b5-4ad1-958a-ba9fa41cd957', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748afe58a1b0>]}
[0m23:30:42.455440 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '2a9c450e-78b5-4ad1-958a-ba9fa41cd957', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748aed409dc0>]}
[0m23:30:42.549418 [debug] [MainThread]: Wrote artifact WritableManifest to /workspaces/CI-CD/src/dbt/target/manifest.json
[0m23:30:42.551359 [debug] [MainThread]: Wrote artifact SemanticManifest to /workspaces/CI-CD/src/dbt/target/semantic_manifest.json
[0m23:30:42.566531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '2a9c450e-78b5-4ad1-958a-ba9fa41cd957', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748aed2a7050>]}
[0m23:30:42.567141 [info ] [MainThread]: Found 2 models, 1 seed, 12 data tests, 479 macros
[0m23:30:42.567657 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '2a9c450e-78b5-4ad1-958a-ba9fa41cd957', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748aed174140>]}
[0m23:30:42.569554 [info ] [MainThread]: 
[0m23:30:42.570082 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m23:30:42.570564 [info ] [MainThread]: 
[0m23:30:42.571236 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m23:30:42.572256 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_DBT_DEV_DB'
[0m23:30:42.735936 [debug] [ThreadPool]: Using snowflake connection "list_DBT_DEV_DB"
[0m23:30:42.736564 [debug] [ThreadPool]: On list_DBT_DEV_DB: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:30:42.737029 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m23:30:43.965669 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:30:43.966278 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:30:43.966898 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro list_schemas
[0m23:30:43.967382 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:30:43.968379 [debug] [MainThread]: Connection 'master' was properly closed.
[0m23:30:43.968816 [debug] [MainThread]: Connection 'list_DBT_DEV_DB' was left open.
[0m23:30:43.969261 [debug] [MainThread]: On list_DBT_DEV_DB: No close available on handle
[0m23:30:43.969665 [info ] [MainThread]: 
[0m23:30:43.970157 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 1.40 seconds (1.40s).
[0m23:30:43.970763 [error] [MainThread]: Encountered an error:
Runtime Error
  Database error while listing schemas in database "DBT_DEV_DB"
  Database Error
    290404 (08001): 404 Not Found: post your-account.snowflakecomputing.com:443/session/v1/login-request
[0m23:30:43.972178 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 5.7172093, "process_in_blocks": "79440", "process_kernel_time": 0.767652, "process_mem_max_rss": "207684", "process_out_blocks": "4488", "process_user_time": 4.664661}
[0m23:30:43.972762 [debug] [MainThread]: Command `dbt seed` failed at 23:30:43.972655 after 5.72 seconds
[0m23:30:43.973264 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748afded3e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748aec4dca70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x748ae48bb5c0>]}
[0m23:30:43.973736 [debug] [MainThread]: Flushing usage events
[0m23:30:44.051067 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:38:45.400607 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b282d4c80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b2992eb70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b27621430>]}


============================== 23:38:45.403910 | 78dbdfed-df50-418c-8cde-63d80193d30d ==============================
[0m23:38:45.403910 [info ] [MainThread]: Running with dbt=1.10.10
[0m23:38:45.404650 [debug] [MainThread]: running dbt with arguments {'profiles_dir': '/workspaces/CI-CD/src/dbt', 'version_check': 'True', 'indirect_selection': 'eager', 'quiet': 'False', 'send_anonymous_usage_stats': 'True', 'debug': 'False', 'log_format': 'default', 'warn_error': 'None', 'no_print': 'None', 'target_path': 'None', 'log_cache_events': 'False', 'introspect': 'True', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'fail_fast': 'False', 'empty': 'None', 'use_colors': 'True', 'log_path': '/workspaces/CI-CD/src/dbt/logs', 'invocation_command': 'dbt seed', 'printer_width': '80', 'write_json': 'True'}
[0m23:38:46.115623 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '78dbdfed-df50-418c-8cde-63d80193d30d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b296db2f0>]}
[0m23:38:46.185343 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '78dbdfed-df50-418c-8cde-63d80193d30d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b27621580>]}
[0m23:38:46.186391 [info ] [MainThread]: Registered adapter: snowflake=1.10.0
[0m23:38:46.346134 [debug] [MainThread]: checksum: 502a0dc23e9052e1ae09f7c44ee219ef7a02dfea7e7d66580d54c304c14d553b, vars: {}, profile: , target: , version: 1.10.10
[0m23:38:46.471398 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m23:38:46.471930 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m23:38:46.522449 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '78dbdfed-df50-418c-8cde-63d80193d30d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b16ee0470>]}
[0m23:38:46.605214 [debug] [MainThread]: Wrote artifact WritableManifest to /workspaces/CI-CD/src/dbt/target/manifest.json
[0m23:38:46.607152 [debug] [MainThread]: Wrote artifact SemanticManifest to /workspaces/CI-CD/src/dbt/target/semantic_manifest.json
[0m23:38:46.621810 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '78dbdfed-df50-418c-8cde-63d80193d30d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b16ce1bb0>]}
[0m23:38:46.622415 [info ] [MainThread]: Found 2 models, 1 seed, 12 data tests, 479 macros
[0m23:38:46.622918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '78dbdfed-df50-418c-8cde-63d80193d30d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b17175730>]}
[0m23:38:46.624845 [info ] [MainThread]: 
[0m23:38:46.625372 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m23:38:46.625812 [info ] [MainThread]: 
[0m23:38:46.626509 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m23:38:46.627531 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_DBT_DEV_DB'
[0m23:38:46.670445 [debug] [ThreadPool]: Using snowflake connection "list_DBT_DEV_DB"
[0m23:38:46.671002 [debug] [ThreadPool]: On list_DBT_DEV_DB: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:38:46.671446 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m23:38:47.353179 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:38:47.353766 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:38:47.354377 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro list_schemas
[0m23:38:47.354832 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:38:47.355856 [debug] [MainThread]: Connection 'master' was properly closed.
[0m23:38:47.356326 [debug] [MainThread]: Connection 'list_DBT_DEV_DB' was left open.
[0m23:38:47.356765 [debug] [MainThread]: On list_DBT_DEV_DB: No close available on handle
[0m23:38:47.357202 [info ] [MainThread]: 
[0m23:38:47.357696 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.73 seconds (0.73s).
[0m23:38:47.358325 [error] [MainThread]: Encountered an error:
Runtime Error
  Database error while listing schemas in database "DBT_DEV_DB"
  Database Error
    290404 (08001): 404 Not Found: post your-account.snowflakecomputing.com:443/session/v1/login-request
[0m23:38:47.359392 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 2.0185921, "process_in_blocks": "8", "process_kernel_time": 0.433206, "process_mem_max_rss": "197852", "process_out_blocks": "1096", "process_user_time": 3.038408}
[0m23:38:47.359978 [debug] [MainThread]: Command `dbt seed` failed at 23:38:47.359870 after 2.02 seconds
[0m23:38:47.360494 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b27093080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b16ce3fb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x756b16b873b0>]}
[0m23:38:47.360982 [debug] [MainThread]: Flushing usage events
[0m23:38:47.533750 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:40:18.281965 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a99ce7bc50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a99d48a240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a99c76e300>]}


============================== 23:40:18.285271 | 70b1e7c7-8345-4a48-a403-b926438ddeb0 ==============================
[0m23:40:18.285271 [info ] [MainThread]: Running with dbt=1.10.10
[0m23:40:18.285992 [debug] [MainThread]: running dbt with arguments {'debug': 'False', 'log_path': '/workspaces/CI-CD/src/dbt/logs', 'use_experimental_parser': 'False', 'send_anonymous_usage_stats': 'True', 'profiles_dir': '/workspaces/CI-CD/src/dbt', 'quiet': 'False', 'cache_selected_only': 'False', 'partial_parse': 'True', 'no_print': 'None', 'log_format': 'default', 'printer_width': '80', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'fail_fast': 'False', 'log_cache_events': 'False', 'version_check': 'True', 'empty': 'None', 'warn_error': 'None', 'indirect_selection': 'eager', 'invocation_command': 'dbt seed', 'write_json': 'True', 'use_colors': 'True'}
[0m23:40:18.974475 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '70b1e7c7-8345-4a48-a403-b926438ddeb0', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a98c78f6b0>]}
[0m23:40:19.047609 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '70b1e7c7-8345-4a48-a403-b926438ddeb0', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a99c4f2a20>]}
[0m23:40:19.048627 [info ] [MainThread]: Registered adapter: snowflake=1.10.0
[0m23:40:19.195690 [debug] [MainThread]: checksum: 502a0dc23e9052e1ae09f7c44ee219ef7a02dfea7e7d66580d54c304c14d553b, vars: {}, profile: , target: , version: 1.10.10
[0m23:40:19.322934 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m23:40:19.323646 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m23:40:19.374403 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '70b1e7c7-8345-4a48-a403-b926438ddeb0', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a98c5b4230>]}
[0m23:40:19.459337 [debug] [MainThread]: Wrote artifact WritableManifest to /workspaces/CI-CD/src/dbt/target/manifest.json
[0m23:40:19.461510 [debug] [MainThread]: Wrote artifact SemanticManifest to /workspaces/CI-CD/src/dbt/target/semantic_manifest.json
[0m23:40:19.475231 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '70b1e7c7-8345-4a48-a403-b926438ddeb0', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a98c3b3a10>]}
[0m23:40:19.475819 [info ] [MainThread]: Found 2 models, 1 seed, 12 data tests, 479 macros
[0m23:40:19.476346 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '70b1e7c7-8345-4a48-a403-b926438ddeb0', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a98c620aa0>]}
[0m23:40:19.478256 [info ] [MainThread]: 
[0m23:40:19.478772 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m23:40:19.479254 [info ] [MainThread]: 
[0m23:40:19.479901 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m23:40:19.480902 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_DBT_DEV_DB'
[0m23:40:19.527694 [debug] [ThreadPool]: Using snowflake connection "list_DBT_DEV_DB"
[0m23:40:19.528291 [debug] [ThreadPool]: On list_DBT_DEV_DB: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:40:19.528733 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m23:40:20.241620 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:40:20.242197 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:40:20.242718 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro list_schemas
[0m23:40:20.243185 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:40:20.244157 [debug] [MainThread]: Connection 'master' was properly closed.
[0m23:40:20.244573 [debug] [MainThread]: Connection 'list_DBT_DEV_DB' was left open.
[0m23:40:20.244966 [debug] [MainThread]: On list_DBT_DEV_DB: No close available on handle
[0m23:40:20.245404 [info ] [MainThread]: 
[0m23:40:20.245840 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.77 seconds (0.77s).
[0m23:40:20.246443 [error] [MainThread]: Encountered an error:
Runtime Error
  Database error while listing schemas in database "DBT_DEV_DB"
  Database Error
    290404 (08001): 404 Not Found: post your-account.snowflakecomputing.com:443/session/v1/login-request
[0m23:40:20.247514 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 2.0256119, "process_in_blocks": "0", "process_kernel_time": 0.44877, "process_mem_max_rss": "198604", "process_out_blocks": "1096", "process_user_time": 2.994798}
[0m23:40:20.248072 [debug] [MainThread]: Command `dbt seed` failed at 23:40:20.247965 after 2.03 seconds
[0m23:40:20.248567 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a99c6400b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a98c3b3e60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x70a98c7b2d80>]}
[0m23:40:20.249031 [debug] [MainThread]: Flushing usage events
[0m23:40:20.337448 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:42:59.502676 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d237a5970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d23974e60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d23d1f2c0>]}


============================== 23:42:59.505952 | 64272947-f8c6-4b2b-a9ce-5a633ffc7902 ==============================
[0m23:42:59.505952 [info ] [MainThread]: Running with dbt=1.10.10
[0m23:42:59.506611 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'log_path': '/workspaces/CI-CD/src/dbt/logs', 'introspect': 'True', 'debug': 'False', 'static_parser': 'True', 'printer_width': '80', 'log_cache_events': 'False', 'fail_fast': 'False', 'log_format': 'default', 'warn_error': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'empty': 'None', 'invocation_command': 'dbt seed', 'no_print': 'None', 'partial_parse': 'True', 'version_check': 'True', 'send_anonymous_usage_stats': 'True', 'cache_selected_only': 'False', 'use_experimental_parser': 'False', 'quiet': 'False', 'profiles_dir': '/workspaces/CI-CD/src/dbt', 'use_colors': 'True', 'write_json': 'True', 'indirect_selection': 'eager'}
[0m23:43:00.202535 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '64272947-f8c6-4b2b-a9ce-5a633ffc7902', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d13419a90>]}
[0m23:43:00.271761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '64272947-f8c6-4b2b-a9ce-5a633ffc7902', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d132c7290>]}
[0m23:43:00.272795 [info ] [MainThread]: Registered adapter: snowflake=1.10.0
[0m23:43:00.428145 [debug] [MainThread]: checksum: 502a0dc23e9052e1ae09f7c44ee219ef7a02dfea7e7d66580d54c304c14d553b, vars: {}, profile: , target: , version: 1.10.10
[0m23:43:00.573006 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m23:43:00.573547 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m23:43:00.623285 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '64272947-f8c6-4b2b-a9ce-5a633ffc7902', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d130e9c70>]}
[0m23:43:00.706908 [debug] [MainThread]: Wrote artifact WritableManifest to /workspaces/CI-CD/src/dbt/target/manifest.json
[0m23:43:00.708779 [debug] [MainThread]: Wrote artifact SemanticManifest to /workspaces/CI-CD/src/dbt/target/semantic_manifest.json
[0m23:43:00.721959 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '64272947-f8c6-4b2b-a9ce-5a633ffc7902', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d12c2c650>]}
[0m23:43:00.722558 [info ] [MainThread]: Found 2 models, 1 seed, 12 data tests, 479 macros
[0m23:43:00.723054 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '64272947-f8c6-4b2b-a9ce-5a633ffc7902', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d12e531d0>]}
[0m23:43:00.724941 [info ] [MainThread]: 
[0m23:43:00.725464 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m23:43:00.725902 [info ] [MainThread]: 
[0m23:43:00.726559 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m23:43:00.727551 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_DBT_DEV_DB'
[0m23:43:00.774042 [debug] [ThreadPool]: Using snowflake connection "list_DBT_DEV_DB"
[0m23:43:00.774868 [debug] [ThreadPool]: On list_DBT_DEV_DB: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:43:00.775546 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m23:43:01.512166 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:43:01.512758 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:43:01.513356 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro list_schemas
[0m23:43:01.513796 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:43:01.514818 [debug] [MainThread]: Connection 'master' was properly closed.
[0m23:43:01.515312 [debug] [MainThread]: Connection 'list_DBT_DEV_DB' was left open.
[0m23:43:01.515770 [debug] [MainThread]: On list_DBT_DEV_DB: No close available on handle
[0m23:43:01.516219 [info ] [MainThread]: 
[0m23:43:01.516702 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.79 seconds (0.79s).
[0m23:43:01.517330 [error] [MainThread]: Encountered an error:
Runtime Error
  Database error while listing schemas in database "DBT_DEV_DB"
  Database Error
    290404 (08001): 404 Not Found: post your-account.snowflakecomputing.com:443/session/v1/login-request
[0m23:43:01.518416 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 2.0758731, "process_in_blocks": "0", "process_kernel_time": 0.407128, "process_mem_max_rss": "198452", "process_out_blocks": "1104", "process_user_time": 3.088386}
[0m23:43:01.518994 [debug] [MainThread]: Command `dbt seed` failed at 23:43:01.518886 after 2.08 seconds
[0m23:43:01.519510 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d23560440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d13057e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2d13057ec0>]}
[0m23:43:01.519996 [debug] [MainThread]: Flushing usage events
[0m23:43:01.638139 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:45:32.494389 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398bc8c8c20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398bcd11700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398bbcd2c00>]}


============================== 23:45:32.497664 | c794104f-73f5-477a-9223-5670aaff0d6e ==============================
[0m23:45:32.497664 [info ] [MainThread]: Running with dbt=1.10.10
[0m23:45:32.498352 [debug] [MainThread]: running dbt with arguments {'log_cache_events': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'write_json': 'True', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'target_path': 'None', 'static_parser': 'True', 'partial_parse': 'True', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'invocation_command': 'dbt seed', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'profiles_dir': '/workspaces/CI-CD/src/dbt', 'version_check': 'True', 'log_path': '/workspaces/CI-CD/src/dbt/logs', 'printer_width': '80', 'empty': 'None', 'use_colors': 'True'}
[0m23:45:33.187613 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'c794104f-73f5-477a-9223-5670aaff0d6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398ac525340>]}
[0m23:45:33.257032 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'c794104f-73f5-477a-9223-5670aaff0d6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398aca63920>]}
[0m23:45:33.258066 [info ] [MainThread]: Registered adapter: snowflake=1.10.0
[0m23:45:33.407325 [debug] [MainThread]: checksum: 502a0dc23e9052e1ae09f7c44ee219ef7a02dfea7e7d66580d54c304c14d553b, vars: {}, profile: , target: , version: 1.10.10
[0m23:45:33.512187 [info ] [MainThread]: Unable to do partial parsing because profile has changed
[0m23:45:33.512897 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'c794104f-73f5-477a-9223-5670aaff0d6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398ab9f3620>]}
[0m23:45:34.996223 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'c794104f-73f5-477a-9223-5670aaff0d6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398ab25ea20>]}
[0m23:45:35.082385 [debug] [MainThread]: Wrote artifact WritableManifest to /workspaces/CI-CD/src/dbt/target/manifest.json
[0m23:45:35.084454 [debug] [MainThread]: Wrote artifact SemanticManifest to /workspaces/CI-CD/src/dbt/target/semantic_manifest.json
[0m23:45:35.097958 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'c794104f-73f5-477a-9223-5670aaff0d6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398aafcc470>]}
[0m23:45:35.098555 [info ] [MainThread]: Found 2 models, 1 seed, 12 data tests, 479 macros
[0m23:45:35.099046 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'c794104f-73f5-477a-9223-5670aaff0d6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398ab050230>]}
[0m23:45:35.100990 [info ] [MainThread]: 
[0m23:45:35.101645 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m23:45:35.102369 [info ] [MainThread]: 
[0m23:45:35.103309 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m23:45:35.104319 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_DBT_DEV_DB'
[0m23:45:35.144893 [debug] [ThreadPool]: Using snowflake connection "list_DBT_DEV_DB"
[0m23:45:35.145619 [debug] [ThreadPool]: On list_DBT_DEV_DB: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:45:35.146339 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m23:45:37.584614 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: show terse schemas in database DBT_DEV_DB
    limit 10000
/* {"app": "dbt", "dbt_version": "1.10.10", "profile_name": "default", "target_name": "dev", "connection_name": "list_DBT_DEV_DB"} */
[0m23:45:37.585154 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:45:37.585692 [debug] [ThreadPool]: Snowflake adapter: Error running SQL: macro list_schemas
[0m23:45:37.586129 [debug] [ThreadPool]: Snowflake adapter: Rolling back transaction.
[0m23:45:37.587132 [debug] [MainThread]: Connection 'master' was properly closed.
[0m23:45:37.587634 [debug] [MainThread]: Connection 'list_DBT_DEV_DB' was left open.
[0m23:45:37.588195 [debug] [MainThread]: On list_DBT_DEV_DB: No close available on handle
[0m23:45:37.588651 [info ] [MainThread]: 
[0m23:45:37.589270 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 2.49 seconds (2.49s).
[0m23:45:37.589897 [error] [MainThread]: Encountered an error:
Runtime Error
  Database error while listing schemas in database "DBT_DEV_DB"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
    Verify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
    To further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
[0m23:45:37.590966 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 5.156779, "process_in_blocks": "0", "process_kernel_time": 0.430172, "process_mem_max_rss": "207204", "process_out_blocks": "2112", "process_user_time": 4.457421}
[0m23:45:37.591561 [debug] [MainThread]: Command `dbt seed` failed at 23:45:37.591454 after 5.16 seconds
[0m23:45:37.592005 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398ab04db80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398ab2782f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7398ab27ae40>]}
[0m23:45:37.592482 [debug] [MainThread]: Flushing usage events
[0m23:45:37.712478 [debug] [MainThread]: An error was encountered while trying to flush usage events
